application: ucc-timetabler
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.1"

- name: lxml
  version: "2.3"

handlers:
- url: /static
  static_dir: static

- url: /landing
  static_files: landing.html
  upload: landing.html

- url: .*
  script: main.app
